name: Deploy Next.js to Azure Web App

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          # Verifica esplicita che express sia installato
          npm install express

      - name: Build Next.js app
        run: npm run build

      - name: Verify build and server
        run: |
          echo "Verifying build output and server configuration..."
          ls -la
          ls -la .next || echo "No .next directory!"
          cat server.js || echo "No server.js found!"

      - name: Zip artifact for deployment
        run: |
          zip -r release.zip . \
            --exclude "node_modules/*" \
            --exclude ".git/*"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-nextjs-webapp"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip
