name: Deploy Next.js to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Start Deployment
        run: |
          echo "Starting deployment process"
          echo "Node version:"
          node -v
          echo "NPM version:"
          npm -v

      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Verify package.json
        run: |
          echo "Current working directory:"
          pwd
          echo "Contents of directory:"
          ls -la
          echo "Package.json content:"
          cat package.json

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Installed dependencies:"
          npm list --depth=0

      - name: Build Next.js app
        run: |
          echo "Starting build process..."
          npm run build
          echo "Build completed. Contents of .next directory:"
          ls -la .next

      - name: Prepare deployment package
        run: |
          echo "Creating deployment package..."
          zip -r release.zip ./* .next
          echo "Deployment package size:"
          ls -lh release.zip

      - name: Deploy to Azure Web App
        id: deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: "my-nextjs-webapp"
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip

      - name: Post Deployment Status
        if: always()
        run: |
          echo "Deployment Status: ${{ steps.deploy.outcome }}"
          echo "To check the logs on Azure, visit:"
          echo "https://portal.azure.com/#@/resource/subscriptions/YOUR-SUBSCRIPTION-ID/resourceGroups/my-nextjs-group/providers/Microsoft.Web/sites/my-nextjs-webapp/logStream"

      - name: Handle Deployment Failure
        if: failure()
        run: |
          echo "Deployment failed. Here's some debugging information:"
          echo "GitHub Action Run URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "Last few entries from npm logs (if available):"
          cat ~/.npm/_logs/* 2>/dev/null || echo "No npm logs found"
