name: Deploy Next.js to Azure Web App

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm ci
          echo "Installing express explicitly..."
          npm install express --save
          
      - name: Build Next.js app
        run: |
          echo "Building Next.js app..."
          npm run build
          echo "Build completed"
        
      - name: List files before zip
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Server.js content:"
          cat server.js
          echo "Package.json content:"
          cat package.json
          
      - name: Zip with production dependencies
        run: |
          echo "Creating production node_modules..."
          rm -rf node_modules
          npm ci --production
          
          echo "Creating deployment package..."
          zip -r release.zip . \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "node_modules/.cache/*"
          
          echo "Final zip contents:"
          unzip -l release.zip
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'my-nextjs-webapp'
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: release.zip
          
      - name: Post-deployment verification
        if: always()
        run: |
          echo "Deployment completed with status: ${{ job.status }}"
          echo "Check the following URL after a few minutes:"
          echo "https://my-nextjs-webapp.azurewebsites.net"